import type { ProjectRow } from "@/types/project";

export function mapProjectToDb(row: Record<string, unknown>) {
  return {
    record_id: row.record_id,
    project_id: row.project_id,
    project_owner: row.project_owner,
    activity_type: row.activity_type,
    client_name: row.client_name,
    so_no: row.so_no,
    fg_code: row.fg_code,
    product_name: row.product_name,
    batch_instance_id: row.batch_instance_id,
    unique_batch: row.unique_batch,
    mo_instance_id: row.mo_instance_id,
    mo_control_no: row.mo_control_no,
    po_instance_id: row.po_instance_id,
    po_control_no: row.po_control_no,
    fg_month: row.fg_month,
    business_unit: row.business_unit,
    updateddocsver: row.updatedDocsVer,
    order_quantity: row.order_quantity,
    uom: row.uom,
    prod_ver: row.prod_ver,
    cnf_reference: row.cnf_reference,
    qrmr_ref_no: row.qrmr_ref_no,
    qrmr_status: row.qrmr_status,
    qrmr_target_date: row.qrmr_target_date,
    change_description: row.change_description,
    cnf_status: row.cnf_status,
    client_approval_target_date: row.client_approval_target_date,
    remarks: row.remarks,
    cnf_entries_json: row.cnf_entries_json,
    manufacturing_start_week: row.manufacturing_start_week,
    mo_bmr_po_submission_status: row.mo_bmr_po_submission_status,
    mo_bmr_po_target_date: row.mo_bmr_po_target_date,
    mo_bmr_po_activation_status: row.mo_bmr_po_activation_status,
    mo_bmr_po_activation_date: row.mo_bmr_po_activation_date,
    protocol_no: row.protocol_no,
    protocol_status: row.protocol_Status,
    protocol_target_date: row.protocol_target_date,
    val_activity: row.Val_Activity,
    val_stability: row.Val_Stability,
    val_batch_seq_no: row.Val_Batch_Seq_No,
    val_strategy: row.Val_Strategy,
    val_strategy_remarks: row.Val_Strategy_remarks,
    val_interim_report_no: row.val_interim_report_no,
    val_interim_report_status: row.val_interim_report_status,
    val_interim_report_target_date: row.val_interim_report_target_date,
    validation_report_no: row.validation_report_no,
    validation_report_status: row.validation_report_status,
    validation_report_target_date: row.validation_report_target_date,
    endorsement_report_no: row.endorsement_report_no,
    endorsement_report_status: row.endorsement_report_status,
    endorsement_acceptance_target_date: row.endorsement_acceptance_target_date,
    val_report_no: row.validation_report_no,
    report_sub_status: row.validation_report_status,
    report_target_date: row.validation_report_target_date,
    ar_availability_date: row.ar_availability_date,
    packaging_schedule: row.packaging_schedule,
    final_status: row.final_status,
    final_status_other: row.final_status_other,
    created_by: row.created_by,
    created_at: row.created_at,
    updated_by: row.updated_by,
    updated_at: row.updated_at,
    is_active: row.is_active,
  };
}

export function mapDbToProject(row: Record<string, unknown>): ProjectRow {
  return {
    record_id: String(row.record_id ?? ""),
    project_id: String(row.project_id ?? ""),
    project_owner: String(row.project_owner ?? ""),
    activity_type: String(row.activity_type ?? ""),
    client_name: String(row.client_name ?? ""),
    so_no: String(row.so_no ?? ""),
    fg_code: String(row.fg_code ?? ""),
    product_name: String(row.product_name ?? ""),
    batch_instance_id: String(row.batch_instance_id ?? ""),
    unique_batch: String(row.unique_batch ?? ""),
    mo_instance_id: String(row.mo_instance_id ?? ""),
    mo_control_no: String(row.mo_control_no ?? ""),
    po_instance_id: String(row.po_instance_id ?? ""),
    po_control_no: String(row.po_control_no ?? ""),
    fg_month: String(row.fg_month ?? ""),
    business_unit: String(row.business_unit ?? ""),
    updatedDocsVer: String(row.updateddocsver ?? ""),
    order_quantity: String(row.order_quantity ?? ""),
    uom: String(row.uom ?? ""),
    prod_ver: String(row.prod_ver ?? ""),
    cnf_reference: String(row.cnf_reference ?? ""),
    qrmr_ref_no: String(row.qrmr_ref_no ?? ""),
    qrmr_status: String(row.qrmr_status ?? ""),
    qrmr_target_date: String(row.qrmr_target_date ?? ""),
    risk_control: String(row.risk_control ?? ""),
    change_description: String(row.change_description ?? ""),
    cnf_status: String(row.cnf_status ?? ""),
    client_approval_target_date: String(row.client_approval_target_date ?? ""),
    remarks: String(row.remarks ?? ""),
    cnf_entries_json: String(row.cnf_entries_json ?? "[]"),
    manufacturing_start_week: String(row.manufacturing_start_week ?? ""),
    mo_bmr_po_submission_status: String(row.mo_bmr_po_submission_status ?? ""),
    mo_bmr_po_target_date: String(row.mo_bmr_po_target_date ?? ""),
    mo_bmr_po_activation_status: String(row.mo_bmr_po_activation_status ?? ""),
    mo_bmr_po_activation_date: String(row.mo_bmr_po_activation_date ?? ""),
    protocol_no: String(row.protocol_no ?? ""),
    protocol_Status: String(row.protocol_status ?? ""),
    protocol_target_date: String(row.protocol_target_date ?? ""),
    Val_Activity: String(row.val_activity ?? ""),
    Val_Stability: String(row.val_stability ?? ""),
    Val_Batch_Seq_No: String(row.val_batch_seq_no ?? ""),
    Val_Strategy: String(row.val_strategy ?? ""),
    Val_Strategy_remarks: String(row.val_strategy_remarks ?? ""),
    val_interim_report_no: String(row.val_interim_report_no ?? ""),
    val_interim_report_status: String(row.val_interim_report_status ?? ""),
    val_interim_report_target_date: String(row.val_interim_report_target_date ?? ""),
    validation_report_no: String(row.validation_report_no ?? row.val_report_no ?? ""),
    validation_report_status: String(row.validation_report_status ?? row.report_sub_status ?? ""),
    validation_report_target_date: String(row.validation_report_target_date ?? row.report_target_date ?? ""),
    endorsement_report_no: String(row.endorsement_report_no ?? ""),
    endorsement_report_status: String(row.endorsement_report_status ?? ""),
    endorsement_acceptance_target_date: String(row.endorsement_acceptance_target_date ?? ""),
    ar_availability_date: String(row.ar_availability_date ?? ""),
    packaging_schedule: String(row.packaging_schedule ?? ""),
    final_status: String(row.final_status ?? ""),
    final_status_other: String(row.final_status_other ?? ""),
    created_by: String(row.created_by ?? ""),
    created_at: String(row.created_at ?? ""),
    updated_by: String(row.updated_by ?? ""),
    updated_at: String(row.updated_at ?? ""),
    is_active: Boolean(row.is_active),
  };
}

export {
  mapDbToSupport,
  mapSupportToDb,
} from "@/lib/endorsementMappers";

