import { AM_CNF_ENTRY_KEYS, CNF_ENTRY_KEYS } from "@/lib/constants";
import type { UserRole } from "@/types";

export type ProjectTab = "AM/BM/PL" | "QA" | "PP" | "TSD" | "VAL" | "QC";

export const PROJECT_TABS: ProjectTab[] = ["AM/BM/PL", "QA", "PP", "TSD", "VAL", "QC"];

export type ProjectFieldType =
  | "readonly"
  | "text"
  | "numeric"
  | "order_quantity"
  | "alphanumeric"
  | "textarea"
  | "select"
  | "date"
  | "month";

export interface ProjectFieldDef {
  key: string;
  label: string;
  type: ProjectFieldType;
  role: ProjectTab | "System";
  tooltip?: string;
  registry?: string;
  span?: 1 | 2 | 3;
  copyFromFirst?: boolean;
  required?: boolean;
  capitalizeWords?: boolean;
  projectLevelVal?: boolean;
}

export const HEADER_FIELDS: ProjectFieldDef[] = [
  { key: "project_id", label: "Project ID", type: "readonly", role: "System", tooltip: "Auto-generated by the system. Format: PROJ-YYYY-001." },
  { key: "project_owner", label: "Project Owner", type: "text", role: "AM/BM/PL", tooltip: "Set automatically from your profile first name when you create a project. Admins may assign any owner." },
  { key: "activity_type", label: "Activity Type", type: "select", role: "AM/BM/PL", registry: "activity_type", tooltip: "Select PILOT/TRIAL, TRC, or VAL/VER." },
  { key: "client_name", label: "Client Name", type: "text", role: "AM/BM/PL", capitalizeWords: true, tooltip: "Client or principal name." },
  { key: "fg_code", label: "FG Code", type: "alphanumeric", role: "AM/BM/PL", tooltip: "Finished goods code (letters, numbers, hyphens)." },
  { key: "product_name", label: "Product Name", type: "text", role: "AM/BM/PL", span: 3, capitalizeWords: true, tooltip: "Product or project name." },
];

export const BATCH_FIELDS: ProjectFieldDef[] = [
  { key: "unique_batch", label: "Unique Batch", type: "alphanumeric", role: "AM/BM/PL", tooltip: "Unique batch identifier (e.g. 2026BAKS-1)." },
];

export const MO_FIELDS: ProjectFieldDef[] = [
  { key: "mo_control_no", label: "MO Control No.", type: "alphanumeric", role: "AM/BM/PL", tooltip: "Manufacturing order control number (alphanumeric)." },
];

export const PROJECT_LEVEL_PO_FIELDS = new Set<string>();

export const PROJECT_LEVEL_VAL_FIELDS = new Set([
  "protocol_no",
  "protocol_Status",
  "protocol_target_date",
  "validation_report_no",
  "validation_report_status",
  "validation_report_target_date",
  "endorsement_report_no",
  "endorsement_report_status",
  "endorsement_acceptance_target_date",
]);

export const PO_FIELDS: ProjectFieldDef[] = [
  { key: "so_no", label: "SO No.", type: "alphanumeric", role: "AM/BM/PL", tooltip: "Sales order number (alphanumeric)." },
  { key: "po_control_no", label: "PO Control No.", type: "alphanumeric", role: "AM/BM/PL", required: true, tooltip: "PO control number (letters, numbers, hyphens, parentheses)." },
  {
    key: "fg_month",
    label: "FG Month",
    type: "month",
    role: "AM/BM/PL",
    tooltip:
      "Target finished-goods month. After save, only Admin and AM/BM/PL can change it; a reason is required and logged to Lessons Learned.",
  },
  { key: "business_unit", label: "Business Unit", type: "select", role: "AM/BM/PL", registry: "business_unit", tooltip: "CM, BM, or PL." },
  { key: "updatedDocsVer", label: "Updated Docs/Ver", type: "select", role: "AM/BM/PL", registry: "updatedDocsVer", tooltip: "Indicate if documents/version were updated (Yes/No)." },
  {
    key: "prod_ver",
    label: "Prod. Ver.",
    type: "alphanumeric",
    role: "AM/BM/PL",
    tooltip: "Product version (alphanumeric).",
  },
  {
    key: "order_quantity",
    label: "Order Quantity",
    type: "order_quantity",
    role: "AM/BM/PL",
    tooltip: "Input numerical value only. Use commas (,) as thousands separators and up to two decimal places.",
  },
  {
    key: "uom",
    label: "Uom",
    type: "select",
    role: "AM/BM/PL",
    registry: "uom",
    tooltip: "Select the unit of measure: BXs, BTs, Sachets, Unit, Tubes, Blisters, Strips, Packs, Units, or Pcs.",
  },
  { key: "cnf_reference", label: "CNF Reference", type: "alphanumeric", role: "AM/BM/PL", copyFromFirst: true, tooltip: "CNF reference number. Use Copy from 1st PO when applicable." },
  { key: "change_description", label: "Change Description", type: "textarea", role: "AM/BM/PL", span: 3, tooltip: "Describe the change." },
  { key: "cnf_status", label: "CNF Status", type: "select", role: "AM/BM/PL", registry: "cnf_status", tooltip: "CNF Creation, Routing, Client Approval, or Approved." },
  { key: "client_approval_target_date", label: "Client Approval Target", type: "date", role: "AM/BM/PL", tooltip: "Target date for client approval." },
  { key: "remarks", label: "Remarks", type: "textarea", role: "AM/BM/PL", span: 3, tooltip: "General remarks." },
  { key: "manufacturing_start_week", label: "Manufacturing Start Week", type: "date", role: "PP", tooltip: "Planned manufacturing start week." },
  { key: "mo_bmr_po_submission_status", label: "MO/BMR/PO Submission", type: "select", role: "TSD", registry: "yn_status", tooltip: "Submission status (Y/N)." },
  { key: "mo_bmr_po_target_date", label: "MO/BMR/PO Target Date", type: "date", role: "TSD", tooltip: "Target date for MO/BMR/PO submission." },
  { key: "mo_bmr_po_activation_status", label: "MO/BMR/PO Activation", type: "select", role: "TSD", registry: "yn_status", tooltip: "Activation status (Y/N)." },
  { key: "mo_bmr_po_activation_date", label: "MO/BMR/PO Activation Date", type: "date", role: "TSD", tooltip: "Activation date for MO/BMR/PO." },
  {
    key: "tsd_remarks",
    label: "Remarks",
    type: "textarea",
    role: "TSD",
    span: 3,
    tooltip: "Long-text remarks for MO/BMR/PO.",
  },
  { key: "protocol_no", label: "Protocol No.", type: "alphanumeric", role: "VAL", projectLevelVal: true, tooltip: "Validation protocol number. One value per project." },
  { key: "protocol_Status", label: "Protocol Status", type: "select", role: "VAL", registry: "doc_status", projectLevelVal: true, tooltip: "Protocol document status." },
  { key: "protocol_target_date", label: "Protocol Target Date", type: "date", role: "VAL", projectLevelVal: true, tooltip: "Protocol target completion date." },
  { key: "Val_Activity", label: "Val Activity", type: "select", role: "VAL", registry: "Val_Activity", tooltip: "VAL, VER, CHAR, or COMML." },
  { key: "Val_Stability", label: "Val Stability", type: "select", role: "VAL", registry: "Val_Stability", tooltip: "Is this batch for stability? Yes/No." },
  { key: "Val_Batch_Seq_No", label: "Val Batch Seq No.", type: "select", role: "VAL", registry: "Val_Batch_Seq_No", tooltip: "Batch sequence number (1, 2, 3, ...)." },
  { key: "Val_Strategy", label: "Val Strategy", type: "select", role: "VAL", registry: "Val_Strategy", copyFromFirst: true, tooltip: "Concurrent or Prospective strategy." },
  { key: "Val_Strategy_remarks", label: "Val Strategy Remarks", type: "textarea", role: "VAL", span: 3, tooltip: "Describe implementation strategy if change applies to COMML during ongoing study." },
  { key: "val_interim_report_no", label: "Interim Report No.", type: "alphanumeric", role: "VAL", tooltip: "Interim report reference number for this batch." },
  { key: "val_interim_report_status", label: "Interim Report Status", type: "select", role: "VAL", registry: "val_interim_report_status", tooltip: "Interim report workflow status." },
  { key: "val_interim_report_target_date", label: "Interim Report Target Date", type: "date", role: "VAL", tooltip: "Target date for the interim report. Not required when Interim Report Status is Approved or Not Applicable." },
  { key: "validation_report_no", label: "Report No.", type: "alphanumeric", role: "VAL", projectLevelVal: true, tooltip: "Full validation report number. One value per project." },
  { key: "validation_report_status", label: "Report Status", type: "select", role: "VAL", registry: "validation_report_status", projectLevelVal: true, tooltip: "Full validation report workflow status." },
  { key: "validation_report_target_date", label: "Report Target Date", type: "date", role: "VAL", projectLevelVal: true, tooltip: "Target date for the full validation report." },
  { key: "endorsement_report_no", label: "Endorsement Report No.", type: "alphanumeric", role: "VAL", projectLevelVal: true, tooltip: "Endorsement report reference number. One value per project." },
  { key: "endorsement_report_status", label: "Endorsement Report Status", type: "select", role: "VAL", registry: "endorsement_report_status", projectLevelVal: true, tooltip: "Endorsement report workflow status. BMR unlock requires Approved or Not Applicable." },
  { key: "endorsement_acceptance_target_date", label: "Endorsement Target Date", type: "date", role: "VAL", projectLevelVal: true, tooltip: "Target endorsement acceptance date. Defaults to one month after Report Target Date. Not required when Endorsement Report Status is Approved or Not Applicable." },
  { key: "ar_availability_date", label: "AR Availability Date", type: "date", role: "QC", tooltip: "Analytical report availability date." },
  {
    key: "qc_remarks",
    label: "Remarks",
    type: "textarea",
    role: "QC",
    span: 3,
    tooltip: "Long-text remarks for QC / AR availability.",
  },
  { key: "packaging_schedule", label: "Packaging Schedule", type: "date", role: "PP", tooltip: "Planned packaging schedule." },
  { key: "final_status", label: "Final Status", type: "select", role: "PP", registry: "final_status", tooltip: "OPEN, CLOSED, CANCELLED, or Others." },
  {
    key: "final_status_other",
    label: "Remarks",
    type: "textarea",
    role: "PP",
    span: 3,
    tooltip: "Long-text remarks. Required when Final Status is Others or CANCELLED.",
  },
];

export const VAL_TAB_HEADER_FIELD_KEYS = [
  "protocol_no",
  "protocol_Status",
  "protocol_target_date",
  "validation_report_no",
  "validation_report_status",
  "validation_report_target_date",
  "endorsement_report_no",
  "endorsement_report_status",
  "endorsement_acceptance_target_date",
] as const;

export const VAL_TAB_HEADER_FIELDS: ProjectFieldDef[] = VAL_TAB_HEADER_FIELD_KEYS.map(
  (key) => PO_FIELDS.find((field) => field.key === key),
).filter((field): field is ProjectFieldDef => Boolean(field));

export const VAL_TAB_HEADER_PROTOCOL_FIELDS: ProjectFieldDef[] = VAL_TAB_HEADER_FIELDS.slice(0, 3);

export const VAL_TAB_HEADER_REPORT_FIELDS: ProjectFieldDef[] = VAL_TAB_HEADER_FIELDS.slice(3);

export const CNF_FIELDS: ProjectFieldDef[] = PO_FIELDS.filter((field) =>
  (AM_CNF_ENTRY_KEYS as readonly string[]).includes(field.key),
);

export const QA_CNF_FIELDS: ProjectFieldDef[] = [
  {
    key: "cnf_reference",
    label: "CNF Reference",
    type: "readonly",
    role: "QA",
    tooltip: "CNF reference from AM/BM/PL tab (read-only on QA tab).",
  },
  {
    key: "change_description",
    label: "Change Description",
    type: "textarea",
    role: "QA",
    span: 3,
    tooltip: "Change description from AM/BM/PL tab (read-only on QA tab).",
  },
  {
    key: "qrmr_ref_no",
    label: "QRMR No.",
    type: "alphanumeric",
    role: "QA",
    tooltip: "QRMR reference number for this CNF entry.",
  },
  {
    key: "qrmr_status",
    label: "Status",
    type: "select",
    role: "QA",
    registry: "qrmr_status",
    tooltip:
      "QRMR must be Approved or Not Applicable on or before the PO FG Month. Not Applicable disables QRMR No. and Target Date.",
  },
  {
    key: "qrmr_target_date",
    label: "Target Date",
    type: "date",
    role: "QA",
    tooltip:
      "Defaults to the last day of the PO FG Month when FG Month is set. Not required when Status is Approved or Not Applicable.",
  },
  {
    key: "risk_control",
    label: "Risk Control",
    type: "textarea",
    role: "QA",
    span: 3,
    tooltip: "QA can paste risk control stated in the QRMR No.",
  },
];

/** Copied from PO 1 → PO 2+ within the same MO when using "Copy from 1st PO" on AM/BM/PL. */
export const COPY_FROM_FIRST_PO_AM_FIELDS = [
  "fg_month",
  "business_unit",
  "updatedDocsVer",
  "prod_ver",
  "order_quantity",
  "uom",
] as const;

/** Rendered side-by-side in the PO form; order_quantity must precede uom in PO_FIELDS. */
export const PO_ORDER_QUANTITY_UOM_KEYS = ["order_quantity", "uom"] as const;

export const PO_FIELDS_BY_TAB = (tab: ProjectTab): ProjectFieldDef[] =>
  PO_FIELDS.filter(
    (field) => !(CNF_ENTRY_KEYS as readonly string[]).includes(field.key) && field.role === tab,
  );

export function projectTabKey(tab: ProjectTab): string {
  if (tab === "AM/BM/PL") return "am";
  if (tab === "QA") return "qa";
  return tab.toLowerCase();
}

export function tabToFieldGroup(tab: ProjectTab): "am" | "qa" | "pp" | "tsd" | "val" | "qc" {
  const map: Record<ProjectTab, "am" | "qa" | "pp" | "tsd" | "val" | "qc"> = {
    "AM/BM/PL": "am",
    QA: "qa",
    PP: "pp",
    TSD: "tsd",
    VAL: "val",
    QC: "qc",
  };
  return map[tab];
}

/** Default Project Entry role tab for the signed-in user (admin/view → AM/BM/PL). */
export function defaultProjectTabForRole(role: UserRole | null | undefined): ProjectTab {
  switch (role) {
    case "qa":
      return "QA";
    case "pp":
      return "PP";
    case "tsd":
      return "TSD";
    case "val":
      return "VAL";
    case "qc":
      return "QC";
    case "admin":
    case "am_bm_pl":
    case "view":
    default:
      return "AM/BM/PL";
  }
}
